### ISSUE TITLE
Directly use k8s API

### ISSUE THREAD

**Issue by TanguyBaudrin** [germainlefebvre4/ns-killer#19]
Maybe the tool can be more efficient by talking directly to the kubeserver api with a REST call, instead of using the `kubectl` command line tool.

https://github.com/germainlefebvre4/ns-killer/blob/347223cd9478f38a745ace16c37e925a25bdeeb6/main.py#L18

We can replace by this library : https://github.com/kubernetes-client/python/ ?

**Comment by germainlefebvre4** [comment]
Hey Tanguy, thank you for your concern

This is a good opportunity to improve operator performances.

I am dealing with it these days and trying to manage these use cases:
* Delete Kubernetes Namespace (that is already done)
* Delete Helm Chart (and retrieve the helm binary at the same time of kubectl)

**Comment by TanguyBaudrin** [comment]
You're welcome ;)

I'll be working on the k8s rest api call if you want, submitting a PR soon.
